services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
      target: dev
    container_name: twitch_recorder_php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: twitch_recorder_nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    container_name: twitch_recorder_postgres
    environment:
      POSTGRES_DB: twitch_recorder
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: twitch_recorder_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: twitch_recorder_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ".docker/rabbitmq/user.conf:/etc/rabbitmq/conf.d/user.conf:z"

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: