services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
      target: dev
    container_name: twitch_recorder_php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: dev
      APP_SECRET: "!ChangeMe!"
      DATABASE_URL: "postgresql://app:!ChangeMe!@postgres:5432/app?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://redis:6379"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"

  nginx:
    image: nginx:alpine
    container_name: twitch_recorder_nginx
    ports:
      - "8080:80" 
    volumes:
      - ./api:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    container_name: twitch_recorder_postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: twitch_recorder_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: